### ISSUE TITLE
有个问题想请教一下

### ISSUE THREAD

**Issue by ElieenAndBella** [chuiba/garb_alarm_clock#3]
可以通过个性装扮的编号进行查人吗

**Comment by chuiba** [comment]
有几种和编号相关的:
1. 装扮信息 (包括描述, 资源, 库存等)
2. 最近购买记录 (最近30条购买信息, 编号)
3. 个人空间里装扮信息 (包括编号等)
4. 前100号的购买者信息 (已失效)
5. TOP10销量的购买者信息 (部分有)

按照你的描述, 你想要的通过编号查询购买者的信息,
那么只有通过最近购买记录才可以找得到.

所以一般的做法是在开卖的时候疯狂请求购买者信息抓包, 然后将数据汇总.
对于已经卖掉的, 就没有了.
当然你可以尝试找找有没有专门做这些数据汇总的人
